# Site settings
title: Taki Hasan Rafi
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

# Other options
excerpt_separator: "<!--more-->"

# Google Analytics
google_analytics: G-839NFDTDXG
